import { defineObject, FieldType } from 'twenty-sdk/define';

export const DRIVER_UNIVERSAL_IDENTIFIER = '3d0b2c24-fd26-4248-ac9d-aabe0beb6698';

export default defineObject({
  universalIdentifier: DRIVER_UNIVERSAL_IDENTIFIER,
  nameSingular: 'driver',
  namePlural: 'drivers',
  labelSingular: 'Driver',
  labelPlural: 'Drivers',
  icon: 'IconUser',
  labelIdentifierFieldMetadataUniversalIdentifier: 'fd0f1ade-3e70-41e1-9a8e-4e7cc2bbbbf7',
  fields: [
    {
      universalIdentifier: 'fd0f1ade-3e70-41e1-9a8e-4e7cc2bbbbf7',
      name: 'name',
      type: FieldType.FULL_NAME,
      label: 'Full Name',
      icon: 'IconUser',
    },
    {
      universalIdentifier: '20121c7e-1e73-434c-8605-ec7a0d19d75a',
      name: 'phone',
      type: FieldType.PHONES,
      label: 'Phone',
      icon: 'IconPhone',
    },
    {
      universalIdentifier: '3e6a3e13-3eda-4bd3-90ec-4e23784f37cb',
      name: 'email',
      type: FieldType.EMAILS,
      label: 'Email',
      icon: 'IconMail',
      isNullable: true,
    },
    {
      universalIdentifier: '152dab63-f282-409b-ad64-375ab0f9c4c3',
      name: 'companyName',
      type: FieldType.TEXT,
      label: 'Company Name',
      icon: 'IconBuilding',
      isNullable: true,
    },
    {
      universalIdentifier: '05ddc3c8-a83e-4f22-b61c-572496b49658',
      name: 'licenseNumber',
      type: FieldType.TEXT,
      label: 'License Number',
      icon: 'IconId',
      isNullable: true,
    },
    {
      universalIdentifier: '1cbfcf7a-f0a6-4e87-a464-483fa9006242',
      name: 'insuranceProvider',
      type: FieldType.TEXT,
      label: 'Insurance Provider',
      icon: 'IconShield',
      isNullable: true,
    },
    {
      universalIdentifier: '401f3acc-d13d-4038-8b0f-2ad1bd010a1c',
      name: 'dotNumber',
      type: FieldType.TEXT,
      label: 'DOT Number',
      icon: 'IconFileText',
      isNullable: true,
    },
    {
      universalIdentifier: '3124393d-2bb2-4e79-9a46-17645822e0d2',
      name: 'driverType',
      type: FieldType.SELECT,
      label: 'Driver Type',
      icon: 'IconCategory',
      options: [
        { value: 'OWNER_OPERATOR', label: 'Owner Operator', position: 0, color: 'blue' },
        { value: 'FLEET', label: 'Fleet / Company', position: 1, color: 'green' },
        { value: 'CONTRACTOR', label: 'Contractor', position: 2, color: 'orange' },
      ],
    },
    {
      universalIdentifier: '0a4b79ca-6dc6-480c-bcd6-af72065516cd',
      name: 'status',
      type: FieldType.SELECT,
      label: 'Status',
      icon: 'IconStatusChange',
      options: [
        { value: 'ACTIVE', label: 'Active', position: 0, color: 'green' },
        { value: 'INACTIVE', label: 'Inactive', position: 1, color: 'gray' },
        { value: 'BLACKLISTED', label: 'Blacklisted', position: 2, color: 'red' },
      ],
    },
    {
      universalIdentifier: '6acc6ff1-395d-4e01-b9e6-7ddb094d78df',
      name: 'totalRentals',
      type: FieldType.NUMBER,
      label: 'Total Rentals',
      icon: 'IconSum',
      defaultValue: 0,
    },
    {
      universalIdentifier: '15bdd60d-d80c-44fd-9f98-11982bc3d5a9',
      name: 'onTimePaymentRate',
      type: FieldType.NUMBER,
      label: 'On-Time Payment %',
      icon: 'IconPercentage',
      isNullable: true,
    },
    {
      universalIdentifier: 'db978033-7bed-4b75-94a4-77597db24825',
      name: 'referralSource',
      type: FieldType.TEXT,
      label: 'Referral Source',
      icon: 'IconUsers',
      defaultValue: "'web'",
    },
    {
      universalIdentifier: '5331a4ca-0230-476a-b3c3-9009529a52c4',
      name: 'notes',
      type: FieldType.TEXT,
      label: 'Notes',
      icon: 'IconNotes',
      isNullable: true,
    },
  ],
});
