import { defineObject, FieldType } from 'twenty-sdk/define';

export const RENTAL_UNIVERSAL_IDENTIFIER = 'd37f0fc3-38fa-4a87-8c48-6d34281fd7fe';

export default defineObject({
  universalIdentifier: RENTAL_UNIVERSAL_IDENTIFIER,
  nameSingular: 'rental',
  namePlural: 'rentals',
  labelSingular: 'Rental',
  labelPlural: 'Rentals',
  icon: 'IconFileText',
  fields: [
    {
      universalIdentifier: 'a7c6336a-95e8-4ff2-bfaa-bfb99a94c8df',
      name: 'contractNumber',
      type: FieldType.TEXT,
      label: 'Contract Number',
      icon: 'IconHash',
    },
    {
      universalIdentifier: '4f7e5a66-c697-46fb-9e5b-3f43cf445002',
      name: 'startDate',
      type: FieldType.DATE_TIME,
      label: 'Start Date',
      icon: 'IconCalendar',
    },
    {
      universalIdentifier: '012c4785-1aac-4245-ba2b-d923db6c1bab',
      name: 'expectedEndDate',
      type: FieldType.DATE_TIME,
      label: 'Expected End Date',
      icon: 'IconCalendarEvent',
      isNullable: true,
    },
    {
      universalIdentifier: '432fc5ff-43f9-4ffb-8866-5e7ee89f1a3a',
      name: 'actualEndDate',
      type: FieldType.DATE_TIME,
      label: 'Actual End Date',
      icon: 'IconCalendarCheck',
      isNullable: true,
    },
    {
      universalIdentifier: '4dae2afd-b9b5-4a1e-bcb6-217b130e318e',
      name: 'weeklyRate',
      type: FieldType.CURRENCY,
      label: 'Weekly Rate',
      icon: 'IconMoneybag',
    },
    {
      universalIdentifier: 'b4ea8f13-b292-44b2-951c-77a3a316f772',
      name: 'depositPaid',
      type: FieldType.CURRENCY,
      label: 'Deposit Paid',
      icon: 'IconPigMoney',
      defaultValue: "'0'",
    },
    {
      universalIdentifier: 'b938309f-3646-4a3c-9360-3dc0fbf8e993',
      name: 'paymentDay',
      type: FieldType.SELECT,
      label: 'Payment Day',
      icon: 'IconCalendar',
      options: [
        { value: 'MONDAY', label: 'Monday', position: 0, color: 'blue' },
        { value: 'TUESDAY', label: 'Tuesday', position: 1, color: 'green' },
        { value: 'WEDNESDAY', label: 'Wednesday', position: 2, color: 'orange' },
        { value: 'THURSDAY', label: 'Thursday', position: 3, color: 'purple' },
        { value: 'FRIDAY', label: 'Friday', position: 4, color: 'red' },
      ],
    },
    {
      universalIdentifier: 'b06435ad-96d0-44ed-bb7f-2528fa923022',
      name: 'status',
      type: FieldType.SELECT,
      label: 'Status',
      icon: 'IconStatusChange',
      options: [
        { value: 'PENDING', label: 'Pending', position: 0, color: 'yellow' },
        { value: 'ACTIVE', label: 'Active', position: 1, color: 'green' },
        { value: 'OVERDUE', label: 'Overdue', position: 2, color: 'red' },
        { value: 'COMPLETED', label: 'Completed', position: 3, color: 'gray' },
        { value: 'TERMINATED', label: 'Terminated', position: 4, color: 'red' },
      ],
    },
    {
      universalIdentifier: '975f8846-5d48-4495-a643-2a9382e46842',
      name: 'mileageStart',
      type: FieldType.NUMBER,
      label: 'Mileage Start',
      icon: 'IconGauge',
      isNullable: true,
    },
    {
      universalIdentifier: '3f2199f6-8f1b-44f9-bc42-466c1d344870',
      name: 'mileageEnd',
      type: FieldType.NUMBER,
      label: 'Mileage End',
      icon: 'IconGauge',
      isNullable: true,
    },
    {
      universalIdentifier: '47b4b820-9ffb-4053-b5cc-e36a7321bdab',
      name: 'documentsSigned',
      type: FieldType.BOOLEAN,
      label: 'Documents Signed',
      icon: 'IconFileCheck',
      defaultValue: false,
    },
    {
      universalIdentifier: 'b88dcec9-2d48-4779-aabb-f74b7ab1e481',
      name: 'insuranceVerified',
      type: FieldType.BOOLEAN,
      label: 'Insurance Verified',
      icon: 'IconShieldCheck',
      defaultValue: false,
    },
    {
      universalIdentifier: 'e91b1304-7fe2-4d0c-b824-2543d3aea769',
      name: 'notes',
      type: FieldType.TEXT,
      label: 'Notes',
      icon: 'IconNotes',
      isNullable: true,
    },
  ],
});
