import { defineObject, FieldType } from 'twenty-sdk/define';

export const TRUCK_UNIVERSAL_IDENTIFIER = '4b10d065-8d8a-433a-a49c-11000b7b9bfe';

export default defineObject({
  universalIdentifier: TRUCK_UNIVERSAL_IDENTIFIER,
  nameSingular: 'truck',
  namePlural: 'trucks',
  labelSingular: 'Truck',
  labelPlural: 'Trucks',
  icon: 'IconTruck',
  fields: [
    {
      universalIdentifier: '0ac1dd66-2fe2-45e0-96c7-95d69c5ff62b',
      name: 'unitNumber',
      type: FieldType.TEXT,
      label: 'Unit Number',
      icon: 'IconHash',
    },
    {
      universalIdentifier: '7b24b717-c404-4ac4-9efc-90c29d3d72da',
      name: 'vin',
      type: FieldType.TEXT,
      label: 'VIN',
      icon: 'IconBarcode',
      isNullable: true,
    },
    {
      universalIdentifier: '54f284b6-1903-44d0-a5f9-261e0624537b',
      name: 'make',
      type: FieldType.TEXT,
      label: 'Make',
      icon: 'IconSettings',
      defaultValue: "'HINO'",
    },
    {
      universalIdentifier: 'bee12483-b97b-491f-9187-04a4686768b4',
      name: 'model',
      type: FieldType.TEXT,
      label: 'Model',
      icon: 'IconCar',
      isNullable: true,
    },
    {
      universalIdentifier: '48dd8910-be6d-4f86-aff5-0940520f7c6a',
      name: 'year',
      type: FieldType.NUMBER,
      label: 'Year',
      icon: 'IconCalendar',
      isNullable: true,
    },
    {
      universalIdentifier: '341fee35-892b-4c68-b9b0-4b4767dc7fc5',
      name: 'boxLength',
      type: FieldType.TEXT,
      label: 'Box Length',
      icon: 'IconRuler',
      defaultValue: "'26ft'",
    },
    {
      universalIdentifier: '812ef546-3f30-4a76-aebf-e29af1e408b7',
      name: 'mileage',
      type: FieldType.NUMBER,
      label: 'Mileage',
      icon: 'IconGauge',
      defaultValue: 0,
    },
    {
      universalIdentifier: 'd8402155-fa66-4ca1-89d6-7aaaccc0aae1',
      name: 'status',
      type: FieldType.SELECT,
      label: 'Status',
      icon: 'IconStatusChange',
      options: [
        { value: 'AVAILABLE', label: 'Available', position: 0, color: 'green' },
        { value: 'RENTED', label: 'Rented', position: 1, color: 'blue' },
        { value: 'MAINTENANCE', label: 'Maintenance', position: 2, color: 'orange' },
        { value: 'RETIRED', label: 'Retired', position: 3, color: 'red' },
      ],
    },
    {
      universalIdentifier: '6b2d119e-ada3-480b-a348-9944e8883797',
      name: 'weeklyRate',
      type: FieldType.CURRENCY,
      label: 'Weekly Rate',
      icon: 'IconMoneybag',
    },
    {
      universalIdentifier: '894a4b87-a36f-4e6d-8aca-1bfff880c391',
      name: 'depositAmount',
      type: FieldType.CURRENCY,
      label: 'Deposit Amount',
      icon: 'IconPigMoney',
      defaultValue: 0,
    },
    {
      universalIdentifier: '3b4aadbb-c37b-4ed6-b20c-7bee26b315ca',
      name: 'insuranceExpiry',
      type: FieldType.DATE_TIME,
      label: 'Insurance Expiry',
      icon: 'IconShield',
      isNullable: true,
    },
    {
      universalIdentifier: '233233de-df7f-4b28-a9a3-c1707da3b334',
      name: 'registrationExpiry',
      type: FieldType.DATE_TIME,
      label: 'Registration Expiry',
      icon: 'IconFileCheck',
      isNullable: true,
    },
    {
      universalIdentifier: '1a8d3d35-3e02-46e1-a984-b31256b646c1',
      name: 'lastServiceDate',
      type: FieldType.DATE_TIME,
      label: 'Last Service Date',
      icon: 'IconWrench',
      isNullable: true,
    },
    {
      universalIdentifier: '79450d04-a08a-40a2-b872-c82e7337aa8e',
      name: 'nextServiceDue',
      type: FieldType.DATE_TIME,
      label: 'Next Service Due',
      icon: 'IconAlertTriangle',
      isNullable: true,
    },
    {
      universalIdentifier: 'de1b57a1-7c30-43da-8b99-45073d88d446',
      name: 'location',
      type: FieldType.TEXT,
      label: 'Location',
      icon: 'IconMapPin',
      defaultValue: "'Charlotte, NC'",
    },
    {
      universalIdentifier: 'af6bedef-416c-40b1-8019-68d06d12fded',
      name: 'notes',
      type: FieldType.TEXT,
      label: 'Notes',
      icon: 'IconNotes',
      isNullable: true,
    },
  ],
});
